import {
  Heart,
  ClipboardList,
  User,
  Building2,
  DollarSign,
  BarChart2,
  Settings,
  Users,
  Shield,
  FileText,
  LogOut,
  Search,
  Menu,
  X as IconX,
  Bell,
  Eye,
  EyeOff,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Star,
  MapPin,
  Upload,
  Check,
  AlertCircle,
  Copy,
  Mail,
  Loader,
  Plus,
  ArrowRight,
  CheckCircle,
  Calendar,
  CreditCard,
  Clock,
  Wifi,
  Zap,
  Flame,
  Bath,
  Wind,
  Car,
  Bike,
  Camera,
  Fingerprint,
  Monitor,
  Tv,
  UtensilsCrossed,
  WashingMachine,
  Archive,
  BedDouble,
  Droplets,
  House,
  TriangleAlert
} from "lucide-solid";

const X = IconX;
const Home = House;
const Instagram = Camera;

export const ICON_MAP = {
  Home, Heart, ClipboardList, User, Building2, DollarSign,
  BarChart2, Settings, Users, Shield, FileText, LogOut,
  Search, Menu, X, Bell, Eye, EyeOff, ChevronUp,
  ChevronDown, ChevronLeft, ChevronRight, Star, MapPin,
  Upload, Check, AlertCircle, Copy, Instagram, Mail,
  Loader, Plus, ArrowRight, CheckCircle, Calendar,
  CreditCard, Clock, Wifi, Zap, Flame, Bath, Wind,
  Car, Bike, Camera, Fingerprint, Monitor, Tv,
  UtensilsCrossed, WashingMachine, Archive, BedDouble,
  Droplets, House, TriangleAlert,
} as const;

export type IconName = keyof typeof ICON_MAP;

export {
  Home, Heart, ClipboardList, User, Building2, DollarSign,
  BarChart2, Settings, Users, Shield, FileText, LogOut,
  Search, Menu, X, Bell, Eye, EyeOff, ChevronUp,
  ChevronDown, ChevronLeft, ChevronRight, Star, MapPin,
  Upload, Check, AlertCircle, Copy, Instagram, Mail,
  Loader, Plus, ArrowRight, CheckCircle, Calendar,
  CreditCard, Clock, Wifi, Zap, Flame, Bath, Wind,
  Car, Bike, Camera, Fingerprint, Monitor, Tv,
  UtensilsCrossed, WashingMachine, Archive, BedDouble,
  Droplets, House, TriangleAlert,
};
